AWSTemplateFormatVersion: '2010-09-09'
Description: Template will deploy an s3 bucket, Route53Zone & SSL certificate to host a static website
Metadata:
  License: magnet:?xt=urn:btih:1f739d935676111cfff4b4693e3816e664797050&dn=gpl-3.0.txt GPL-v3-or-Later

Parameters:
  SiteName:
    Type: String
    Description: Name for the site
    AllowedPattern: '[a-zA-Z0-9-.]{1,63}'
    ConstraintDescription: must be a valid DNS name.
  CertificateARN:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
      BucketName: !Ref SiteName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub www.${SiteName}
          Protocol: https

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref SiteName
        Enabled: true
        IPV6Enabled: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        Origins:
          - Id: bucket
            # Custom Origin used to allow redirects
            DomainName: !Sub ${SiteName}.s3-website.${AWS::Region}.${AWS::URLSuffix}
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        HttpVersion: http2and3
        DefaultCacheBehavior:
          DefaultTTL: 3600
          TargetOriginId: bucket
          ViewerProtocolPolicy: allow-all
          Compress: True
          ForwardedValues:
            QueryString: False

Outputs:
  CloudfrontDistribution:
    Value: !Ref CloudfrontDistribution
  CNAME:
    Value: !GetAtt CloudfrontDistribution.DomainName
